name: Fetch and Process XML

on: [push]

jobs:
  fetch_and_process:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.RED_FLAG }}  # Personal access token

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: pip install requests

    - name: Fetch XML
      run: python fetch_xml.py

    - name: Add changes to Git
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add sdn_advanced.xml

    - name: Commit changes
      run: git commit -m "Add fetched XML file"

    - name: Push changes
      run: git push
