name: Generate Sanctioned Addresses

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests

    - name: Download XML file
      run: |
        import requests
        url = 'https://www.treasury.gov/ofac/downloads/sanctions/1.0/sdn_advanced.xml'
        response = requests.get(url)
        with open('sdn_advanced.xml', 'w') as file:
            file.write(response.text)
      shell: python

    - name: Create Directory
      run: mkdir "Sanctioned Addresses"

    - name: Run Python script
      run: python process_xml.py ETH -f TXT -path ./Sanctioned\ Addresses/

    - name: Commit and push if it's not a pull request
      if: github.event_name != 'pull_request' 
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .
        git commit -m "Add changes" -a
        git push
      env:
        GH_PAT: ${{ secrets.RED_FLAG }}
