name: Fetch XML and Run Python Scripts

on:
  schedule:
    - cron: '0 0 * * *' # This will run the job every day at midnight

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests

    - name: Fetch XML and Run Python Script
      run: |
        python fetch_and_process.py
