
name: Process XML and Generate Text File

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Download XML
      run: |
        curl -O https://www.treasury.gov/ofac/downloads/sanctions/1.0/sdn_advanced.xml

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Run Python script
      run: |
        mkdir -p "Sanctioned Addresses"
        python process_xml.py ETH -f TXT -path "./Sanctioned Addresses"

    - name: Commit and push if it changed
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .
        git diff --quiet && git diff --staged --quiet || (git commit -m "Update data"; git push)
      env:
        RED_FLAG: ${{ secrets.RED_FLAG }}
